version: '3'
services:
    avatar:
        build:
            context: ./avatar
            dockerfile: Dockerfile
        depends_on:
            - processor
        ports:
            - '5000:5000'
        networks:
            - my_network
    processor:
        build: 
            context: ./processor
            dockerfile: Dockerfile
        depends_on:
            - db
        networks:
            - my_network

    bot:
        build: 
            context: ./bot
            dockerfile: Dockerfile
        depends_on:
            - processor
        env_file:
            - ./bot/.env
        networks:
            - my_network

    chatbot:
        build: 
            context: ./chatbot
            dockerfile: Dockerfile
        depends_on:
            - processor
        networks:
            - my_network
                    
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - my_network

    db-migration:
        build:
            context: ./db-migration
            dockerfile: Dockerfile
        depends_on:
            - db
        networks:
            - my_network
    
    shodan-bot:
        build:
            context: ./shodan-bot
            dockerfile: Dockerfile
        depends_on:
            - processor
        networks:
            - my_network
            
networks:
    my_network:
        driver: "bridge"