version: '3'
services:
    processor:
        build: 
            context: ./processor
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - '8000:8000'
        networks:
            - my_network

    bot:
        build: 
            context: ./bot
            dockerfile: Dockerfile
        depends_on:
            - processor
        env_file:
            - ./bot/.env
        networks:
            - my_network

    db:
        image: postgres
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
            
networks:
    my_network:
        driver: "bridge"